name: postgres
services:
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    env_file:
      - path: .env
    ports:
      - ${DB_PORT:?error}:5432
    volumes:
      - ~/docker/volumes/speautyfayye/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PWD:?error}
      - POSTGRES_USER=${DB_USER:?error}
      - POSTGRES_DB=${DB_NAME:?error}
