name: speautyfayye
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:?error}:${PORT:?error}
    env_file: .env
    networks:
      - speautyfayye-network
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: postgres:14-alpine
    env_file:
      - path: .env
    ports:
      - ${DB_PORT:?error}:5432
    volumes:
      - ~/docker/volumes/speautyfayye/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PWD:?error}
      - POSTGRES_USER=${DB_USER:?error}
      - POSTGRES_DB=${DB_NAME:?error}

networks:
  speautyfayye-network:
    driver: bridge
